<?php
$form = $this->form;
$form->setAttribute('action', $this->url('jobs', array('action' => 'save', 'id' => $this->jid)));
$form->setAttribute('method', 'POST');
$form->setAttribute('novalidate', 'true');
$form->prepare();
?>

            <?php echo $this->form()->openTag($form); ?>
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        <?php echo (!$this->id) ? $this->translate('common.create') : $this->translate('common.edit'); ?>  <?php echo $this->translate('job.entity'); ?>
                    </span>
                    <div class="pull-right">
                        <a role="button" class="btn btn-primary btn-sm" href="<?php echo $this->url('jobs'); ?>">
                            <span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('common.cancel'); ?>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('name')) ?>
                        <?php echo $this->formInput($form->get('name')) ?>
                        <span class="form-errors">
                            <?php echo $this->formElementErrors($form->get('name')) ?>
                        </span>
                    </div>

                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('description')) ?>
                        <?php echo $this->formTextarea($form->get('description')) ?>
                        <span class="form-errors">
                            <?php echo $this->formElementErrors($form->get('description')) ?>
                        </span>
                    </div>

                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('comments')) ?>
                        <?php echo $this->formTextarea($form->get('comments')) ?>
                        <span class="form-errors">
                            <?php echo $this->formElementErrors($form->get('comments')) ?>
                        </span>
                    </div>

                    <div class="form-group">
                        <?php
                        // process the 'data-colour' attribute
                        $options = $form->get('labels')->getValueOptions();
                        foreach ($options as &$option) {
                            $option['attributes']['data-content'] = "<span class='label label-default' style='background-color:" . $option['attributes']['data-colour'] . "'>" . $option['label'] . "</span>";
                        }
                        $form->get('labels')->setValueOptions($options);
                        ?>
                        <?php echo $this->formLabel($form->get('labels')) ?>
                        <?php echo $this->formSelect($form->get('labels')->setAttributes(array('class' => 'selectpicker', 'title' => 'common.select-empty-item-title'))) ?>
                        <span class="form-errors">
                            <?php echo $this->formElementErrors($form->get('labels')) ?>
                        </span>
                    </div>
                </div>
            </div>

            <?php if ($this->identity()->getRole() != \Application\Entity\User::ROLE_CUSTOMER): ?>
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        <?php echo $this->translate('user.role-customer'); ?>
                    </span>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('customer')) ?>
                        <?php echo $this->formSelect($form->get('customer')->setAttributes(array('class' => 'selectpicker', 'title' => 'common.select-empty-item-title'))) ?>
                        <span class="form-errors">
                            <?php echo $this->formElementErrors($form->get('customer')) ?>
                        </span>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        <?php echo $this->translate('job.contract'); ?>
                    </span>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('contractType')) ?>
                        <?php echo $this->formSelect($form->get('contractType')->setAttributes(array('class' => 'selectpicker', 'title' => 'common.select-empty-item-title'))) ?>
                        <span class="form-errors">
                            <?php echo $this->formElementErrors($form->get('contractType')) ?>
                        </span>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('contractRate')) ?>
                        <?php echo $this->formInput($form->get('contractRate')) ?>
                        <span class="form-errors">
                            <?php echo $this->formElementErrors($form->get('contractRate')) ?>
                        </span>
                    </div>
                </div>
            <?php endif; ?>

            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('common.save'); ?>
            </button>

            <?php echo $this->form()->closeTag($form); ?>
