            
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        Case #<?php echo $this->escapeHtml($this->job->getId()); ?>: <?php echo $this->escapeHtml($this->job->getTitle()); ?>
                        <?php foreach ($this->job->getLabels() as $label): ?>
                            <span class="label label-default pull-right" style="background-color: <?php echo $this->escapeHtml($label->getColour()); ?>"><?php echo $this->escapeHtml($label->getName()); ?></span> 
                        <?php endforeach; ?>
                    </span>
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        </thead>
                        <tbody>
                            <tr>
                                <td><strong><?php echo $this->translate('job.created'); ?></strong></td>
                                <td><?php echo $this->job->getCreated()->format('d M Y'); ?></td>
                            </tr>
                            <tr>
                                <td><strong><?php echo $this->translate('job.description'); ?></strong></td>
                                <td><?php echo ($this->job->getDescription()) ? $this->escapeHtml($this->job->getDescription()) : 'None'; ?></td>
                            </tr>
                            <tr>
                                <td><strong><?php echo $this->translate('job.comments'); ?></strong></td>
                                <td><?php echo ($this->job->getComments()) ? $this->escapeHtml($this->job->getComments()) : 'None'; ?></td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <div class="pull-right">
                                        <a role="button" class="btn btn-primary btn-sm" href="<?php echo $this->url('jobs', array('action' => 'save', 'id' => $this->escapeHtml($this->job->getId()))); ?>">
                                            <span class="glyphicon glyphicon-edit"></span> <?php echo $this->translate('common.edit'); ?>
                                        </a>
                                        <a role="button" class="btn btn-danger btn-sm" data-remote="false" data-toggle="modal" data-target="#confirm-modal" href="<?php echo $this->url('jobs', array('action' => 'close', 'id' => $this->escapeHtml($this->job->getId()))); ?>">
                                            <span class="glyphicon glyphicon-eye-close"></span> <?php echo $this->translate('job.close'); ?>
                                        </a>  
                                    </div>                                    
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        Recent Activity
                    </span>
                </div>
                <div class="table-responsive activity-stream">
                    <table class="table">
                        <thead>
                        </thead>
                        <tbody>
                        <?php if (count($this->activities)): ?>
                            <?php foreach ($this->activities as $activity): ?>
                                <?php if ($activity->getOperation() == $activity::OPERATION_UPDATE): ?>
                                    <?php $properties = json_decode($activity->getData(), true); ?>
                                    <?php foreach ($properties as $propertyName => $propertyValues): ?>
                            <tr> 
                                <td>
                                <?php if ($propertyName == 'status'): ?>
                                    <?php if ($propertyValues[1] == 0): ?>
                                        <?php echo sprintf(
                                            $this->translate('activity-stream.closed'), 
                                            '<strong>' . $this->escapeHtml($this->user->getName()) . '</strong>', 
                                            strtolower($this->translate('job.' . $propertyName)) 
                                        ); ?>.                                        
                                    <?php elseif ($propertyValues[1] == 1): ?>
                                        <?php echo sprintf(
                                            $this->translate('activity-stream.opened'), 
                                            '<strong>' . $this->escapeHtml($this->user->getName()) . '</strong>', 
                                            strtolower($this->translate('job.' . $propertyName)) 
                                        ); ?>.  
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php echo sprintf(
                                        $this->translate('activity-stream.updated'), 
                                        '<strong>' . $this->escapeHtml($this->user->getName()) . '</strong>', 
                                        strtolower($this->translate('job.' . $propertyName)), 
                                        !empty($propertyValues[0]) ? '<strong>' . $this->escapeHtml($propertyValues[0]) . '</strong>' : '<strong>(' . $this->translate('activity-stream.empty') . ')</strong>', 
                                        !empty($propertyValues[1]) ? '<strong>' . $this->escapeHtml($propertyValues[1]) . '</strong>' : '<strong>(' . $this->translate('activity-stream.empty') . ')</strong>' 
                                    ); ?>.
                                <?php endif; ?>
                                </td>
                                <td><?php echo $activity->getCreated()->format('d M Y h:i T'); ?></td>
                            </tr>                                                      
                                    <?php endforeach; ?>
                                <?php elseif ($activity->getOperation() == $activity::OPERATION_CREATE): ?>                                    
                            <tr>                               
                                <td><?php echo sprintf($this->translate('activity-stream.created'), '<strong>' . $this->escapeHtml($this->user->getName()) . '</strong>'); ?>.</td>
                                <td><?php echo $activity->getCreated()->format('d M Y h:i T'); ?></td>
                            </tr>
                                <?php elseif ($activity->getOperation() == $activity::OPERATION_DELETE): ?>  
                            <tr>                               
                                <td><?php echo sprintf($this->translate('activity-stream.deleted'), '<strong>' . $this->escapeHtml($this->user->getName()) . '</strong>'); ?>.</td>
                                <td><?php echo $activity->getCreated()->format('d M Y h:i T'); ?></td>
                            </tr>                          
                                <?php elseif ($activity->getOperation() == $activity::OPERATION_ASSOCIATE): ?>  
                                    <?php switch ($activity->getAssociatedEntityType()): 
                                         case 'LABEL': ?>
                                        <?php $properties = json_decode($activity->getData(), true); ?>
                            <tr> 
                                <td>
                                <?php echo sprintf(
                                    $this->translate('activity-stream.associated'), 
                                    '<strong>' . $this->escapeHtml($this->user->getName()) . '</strong>', 
                                    '<span class="label label-default" style="background-color: ' . $properties['colour'] . '">' .  $properties['name']. '</span>',
                                    strtolower($this->translate(strtolower($activity->getAssociatedEntityType()).'.entity'))
                                ); ?>.
                                </td>
                                <td><?php echo $activity->getCreated()->format('d M Y h:i T'); ?></td>
                            </tr>  
                                        <?php break; ?>
                                    <?php endswitch; ?>    
                                <?php elseif ($activity->getOperation() == $activity::OPERATION_DISSOCIATE): ?>  
                                    <?php switch ($activity->getAssociatedEntityType()): 
                                        case 'LABEL': ?>
                                        <?php $properties = json_decode($activity->getData(), true); ?>
                            <tr> 
                                <td>
                                <?php echo sprintf(
                                    $this->translate('activity-stream.dissociated'), 
                                    '<strong>' . $this->escapeHtml($this->user->getName()) . '</strong>', 
                                    '<span class="label label-default" style="background-color: ' . $properties['colour'] . '">' .  $properties['name']. '</span>',
                                    strtolower($this->translate(strtolower($activity->getAssociatedEntityType()).'.entity'))
                                ); ?>.
                                </td>
                                <td><?php echo $activity->getCreated()->format('d M Y h:i T'); ?></td>
                            </tr>  
                                        <?php break; ?>
                                    <?php endswitch; ?>
                                <?php endif; ?>        
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>                               
                                <td colspan="2">No recent activity to report.</td>
                            </tr>                           
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            
            <div class="modal fade" id="confirm-modal" tabindex="-1" role="dialog">
            </div>
