            
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        Case #<?php echo $this->escapeHtml($this->job->getId()); ?>: <?php echo $this->escapeHtml($this->job->getTitle()); ?>
                    </span>
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        </thead>
                        <tbody>
                            <tr>
                                <td><strong><?php echo $this->translate('application.job.created'); ?></strong></td>
                                <td><?php echo $this->job->getCreated()->format('d M Y'); ?></td>
                            </tr>
                            <tr>
                                <td><strong><?php echo $this->translate('application.job.description'); ?></strong></td>
                                <td><?php echo ($this->job->getDescription()) ? $this->escapeHtml($this->job->getDescription()) : 'None'; ?></td>
                            </tr>
                            <tr>
                                <td><strong><?php echo $this->translate('application.job.comments'); ?></strong></td>
                                <td><?php echo ($this->job->getComments()) ? $this->escapeHtml($this->job->getComments()) : 'None'; ?></td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <div class="pull-right">
                                        <a role="button" class="btn btn-primary btn-sm" href="<?php echo $this->url('jobs', array('action' => 'save', 'id' => $this->escapeHtml($this->job->getId()))); ?>">
                                            <span class="glyphicon glyphicon-edit"></span> Edit
                                        </a>
                                        <a role="button" class="btn btn-danger btn-sm" href="<?php echo $this->url('jobs', array('action' => 'delete', 'id' => $this->escapeHtml($this->job->getId()))); ?>">
                                            <span class="glyphicon glyphicon-remove"></span> Remove
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        Recent Activity
                    </span>
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        </thead>
                        <tbody>
                        <?php if (count($this->activities)): ?>
                            <?php foreach ($this->activities as $activity): ?>
                                <?php if ($activity->getOperationType() == $activity::ENTITY_OPERATION_TYPE_UPDATE): ?>
                                    <?php $properties = json_decode($activity->getData(), true); ?>
                                    <?php foreach ($properties as $propertyName => $propertyValues): ?>
                            <tr>                               
                                <td>
                                <?php echo sprintf(
                                    $this->translate('application.activity-stream.updated'), 
                                    '<strong>Unknown User</strong>', 
                                    strtolower($this->translate('application.job.' . $propertyName)), 
                                    !empty($propertyValues[0]) ? '<strong>' . $this->escapeHtml($propertyValues[0]) . '</strong>' : '<strong>(' . $this->translate('application.activity-stream.empty') . ')</strong>', 
                                    !empty($propertyValues[1]) ? '<strong>' . $this->escapeHtml($propertyValues[1]) . '</strong>' : '<strong>(' . $this->translate('application.activity-stream.empty') . ')</strong>' 
                                ); ?>.
                                </td>
                                <td><?php echo $activity->getCreated()->format('d M Y h:i T'); ?></td>
                            </tr>                                                      
                                    <?php endforeach; ?>
                                <?php elseif ($activity->getOperationType() == $activity::ENTITY_OPERATION_TYPE_CREATE): ?>                                    
                            <tr>                               
                                <td><?php echo sprintf($this->translate('application.activity-stream.created'), '<strong>Unknown User</strong>'); ?>.</td>
                                <td><?php echo $activity->getCreated()->format('d M Y h:i T'); ?></td>
                            </tr>                          
                                <?php elseif ($activity->getOperationType() == $activity::ENTITY_OPERATION_TYPE_DELETE): ?>  
                            <tr>                               
                                <td><?php echo sprintf($this->translate('application.activity-stream.deleted'), '<strong>Unknown User</strong>'); ?>.</td>
                                <td><?php echo $activity->getCreated()->format('d M Y h:i T'); ?></td>
                            </tr>                          
                                <?php endif; ?>        
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>                               
                                <td colspan="2">No recent activity to report.</td>
                            </tr>                           
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            