<?php
$form = $this->form;
$form->setAttribute('action', $this->url('jobs.logs', array('action' => 'save', 'jid' => $this->jid, 'id' => $this->id)));
$form->setAttribute('method', 'POST');
$form->setAttribute('novalidate', 'true');
$form->prepare();
?>

            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        <?php echo $this->translate('log.add'); ?>
                    </span>
                    <div class="pull-right">
                        <a role="button" class="btn btn-primary btn-sm" href="<?php echo $this->url('jobs', array('action' => 'view', 'id' => $this->jid)); ?>">
                            <span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('common.cancel'); ?>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form); ?>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('date')) ?>
                            <?php echo $this->formDate($form->get('date')) ?>
                            <span class="form-errors">
                                <?php echo $this->formElementErrors($form->get('date')) ?>
                            </span>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('effort')) ?>
                            <?php echo $this->formInput($form->get('effort')) ?>
                            <span class="form-errors">
                                <?php echo $this->formElementErrors($form->get('effort')) ?>
                            </span>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('description')) ?>
                            <?php echo $this->formInput($form->get('description')) ?>
                            <span class="form-errors">
                                <?php echo $this->formElementErrors($form->get('description')) ?>
                            </span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('common.save'); ?>
                            </button>
                        </div>
                    <?php echo $this->formHidden($form->get('csrf')) ?>
                    <?php echo $this->form()->closeTag($form); ?>
                </div>
            </div>

            <script>
            if (!Modernizr.inputtypes.date) {
                jQuery.getScript("<?php echo $this->basePath('public/components/polyfill/html5-simple-date-input-polyfill/html5-simple-date-input-polyfill.min.js'); ?>");
                $('<link>')
                    .appendTo('head')
                    .attr({type : 'text/css', rel : 'stylesheet'})
                    .attr('href', '<?php echo $this->basePath('public/components/polyfill/html5-simple-date-input-polyfill/html5-simple-date-input-polyfill.css'); ?>');
            }
            </script>