
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title"><?php echo $this->translate('common.alert-action'); ?></h4>
                        </div>
                        <div class="modal-body">
                            <?php echo sprintf($this->translate($this->alertMessage), $this->escapeHtml(strtolower($this->translate($this->entityType . '.entity')))); ?>                   
                        </div>
                        <div class="modal-footer">
                            <div class="form-group text-center">
                                <a role="button" class="btn btn-primary" data-dismiss="modal" href="<?php echo $this->cancelTo; ?>">
                                    <span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('common.close'); ?>
                                </a>
                            </div>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
