<?php        
$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('novalidate', 'true');
$form->prepare();
?>

                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title"><?php echo $this->translate('common.confirm-action'); ?></h4>
                        </div>
                        <div class="modal-body">
                            <?php echo sprintf($this->translate('common.confirm-delete'), $this->escapeHtml($this->translate('common.' . $this->entityType)), '<strong>' . $this->escapeHtml($this->entityDescriptor) . '</strong>'); ?>
                         
                            <?php echo $this->translate('common.no-undo'); ?> <?php echo $this->translate('common.confirm-proceed'); ?>                   
                        </div>
                        <div class="modal-footer">
                            <?php echo $this->form()->openTag($form); ?>
                            <div class="form-group"> 
                                <?php echo $this->formHidden($form->get('confirm')) ?>
                                <span class="form-errors">
                                    <?php echo $this->formElementErrors($form->get('confirm')) ?>
                                </span>
                            </div> 
                          <div class="form-group text-center">
                              <a role="button" class="btn btn-primary" data-dismiss="modal" href="<?php echo $this->escapeHtml($form->get('cancelTo')->getValue()); ?>">
                                  <span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('common.no'); ?>
                              </a>
                              <button type="submit" class="btn btn-danger">
                                  <span class="glyphicon glyphicon-ok"></span> <?php echo $this->translate('common.yes'); ?>
                              </button> 
                          </div>   
                          <?php echo $this->form()->closeTag($form); ?>   
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
