<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="<?php echo $this->basePath('public/components/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->basePath('public/components/bootstrap-select/dist/css/bootstrap-select.min.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->basePath('public/css/app.css'); ?>" rel="stylesheet">
        <?php if ($this->home): ?>
        <link href="<?php echo $this->basePath('public/css/app.home.css'); ?>" rel="stylesheet">
        <?php endif; ?>
        <script src="<?php echo $this->basePath('public/components/jquery/jquery.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('public/components/bootstrap/js/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('public/components/bootstrap-select/dist/js/bootstrap-select.min.js'); ?>"></script>
        <script src="<?php echo $this->basePath('public/components/modernizr/modernizr.js'); ?>"></script>
        <script src="<?php echo $this->basePath('public/js/app.js'); ?>"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <?php if ($this->identity()): ?>
                <li class="active"><a href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('common.dashboard'); ?></a></li>
                <li><a href="<?php echo $this->url('reports'); ?>"><?php echo $this->translate('common.reports'); ?></a></li>
                <?php if ($this->authorize()->isAuthorized($this->identity(), 'config', 'index')): ?>
                <li><a href="<?php echo $this->url('config'); ?>"><?php echo $this->translate('common.settings'); ?></a></li>
                <?php endif; ?>
                <li><a href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('common.logout'); ?></a></li>
                <?php else: ?>
                <li><a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('common.home'); ?></a></li>
                <li><a href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('common.login'); ?></a></li>
                <?php endif; ?>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>

        <div class="container">
            <?php echo $this->content; ?>
            <div class="modal fade" id="confirm-modal" tabindex="-1" role="dialog">
            </div>
            <div class="modal fade" id="alert-modal" tabindex="-1" role="dialog">
            </div>
        </div><!-- /.container -->

    </body>
</html>
