
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title"> <?php echo $this->translate('application.label.current-labels'); ?></span>
                    <div class="pull-right">
                        <a role="button" class="btn btn-primary btn-sm" href="<?php echo $this->url('labels', array('action' => 'save')); ?>">
                            <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('application.common.create'); ?>
                        </a>
                    </div>                    
                </div>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        </thead>
                        <tbody>
                            <?php foreach ($this->labels as $l): ?>
                            <tr>
                                <td><span class="label label-default" style="background-color: <?php echo $this->escapeHtml($l->getColour()); ?>"><?php echo $this->escapeHtml($l->getName()); ?></span></td>
                                <td>
                                    <a role="button" class="btn btn-primary btn-sm" href="<?php echo $this->url('labels', array('action' => 'save', 'id' => $this->escapeHtml($l->getId()))); ?>">
                                        <span class="glyphicon glyphicon-edit"></span> <?php echo $this->translate('application.common.edit'); ?>
                                    </a>
                                </td>
                                <td>
                                    <a role="button" class="btn btn-danger btn-sm" href="<?php echo $this->url('labels', array('action' => 'delete', 'id' => $this->escapeHtml($l->getId()))); ?>">
                                        <span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('application.common.delete'); ?>
                                    </a>
                                </td>
                            </tr>            
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            
