            
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        <?php echo $this->translate('application.label.entity'); ?> <?php echo $this->translate('application.common.id'); ?><?php echo $this->escapeHtml($this->label->getId()); ?>: <?php echo $this->escapeHtml($this->label->getName()); ?>
                    </span>
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        </thead>
                        <tbody>
                            <tr>
                                <td><strong><?php echo $this->translate('application.common.created_on'); ?></strong></td>
                                <td><?php echo $this->label->getCreationTime()->format('d M Y'); ?></td>
                            </tr>
                            <tr>
                                <td><strong><?php echo $this->translate('application.label.colour'); ?></strong></td>
                                <td><?php echo ($this->label->getColour()); ?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="pull-right">
                <a role="button" class="btn btn-primary btn-sm" href="<?php echo $this->url('labels', array('action' => 'save', 'id' => $this->escapeHtml($this->label->getId()))); ?>">
                    <span class="glyphicon glyphicon-edit"></span> <?php echo $this->translate('application.common.edit'); ?>
                </a>
                <a role="button" class="btn btn-danger btn-sm" href="<?php echo $this->url('labels', array('action' => 'delete', 'id' => $this->escapeHtml($this->label->getId()))); ?>">
                    <span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('application.common.remove'); ?>
                </a>
            </div>
                    
