<?php        
$form = $this->form;
$form->setAttribute('action', $this->url('jobs.files', array('action' => 'save', 'jid' => $this->jid)));
$form->setAttribute('method', 'POST');
$form->setAttribute('novalidate', 'true');
$form->prepare();
?>
            
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <span class="panel-title">
                        <?php echo $this->translate('file.add'); ?>
                    </span>
                    <div class="pull-right">
                        <a role="button" class="btn btn-primary btn-sm" href="<?php echo $this->url('jobs', array('action' => 'view', 'id' => $this->jid)); ?>">
                            <span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('common.cancel'); ?>
                        </a>
                    </div>                    
                </div>
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form); ?>
                        <div class="form-group"> 
                            <?php echo $this->formLabel($form->get('file')) ?>
                            <?php echo $this->formFile($form->get('file')) ?>
                            <span class="form-errors">
                                <?php echo $this->formElementErrors($form->get('file')) ?>
                            </span>
                        </div> 

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('common.save'); ?>
                            </button> 
                        </div>	 
                    <?php echo $this->form()->closeTag($form); ?>
                </div>
            </div>