<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <span class="panel-title"> <?php echo $this->translate('common.dashboard'); ?></span>
    </div>
    <div class="panel-body table-responsive">
    	<table class="table table-striped">
    		<tr>
    			<td>
					<a href="<?php echo $this->url('jobs'); ?>">
						<h4><?php echo $this->translate('job.jobs'); ?></h4>
					</a>    				
    			</td>
    		</tr>
    		<tr>
    			<td>
					<a href="<?php echo $this->url('users'); ?>">
						<h4><?php echo $this->translate('user.users'); ?></h4>
					</a>
    			</td>
    		</tr>
    		<tr>
    			<td>
					<a href="<?php echo $this->url('labels'); ?>">
						<h4><?php echo $this->translate('label.labels'); ?></h4>
					</a>
    			</td>
    		</tr>
    	</table>
    </div>
</div>